spring:
  application:
    name: coffeemachine
  profile:
    active: prod

build:
  version: 3.0

account: 
  message: "Wellcome app"
  details:
    name : "ok"
    info : "test"
  phone:
  - "010230306"


