spring:
  application:
    name: coffeemachine
  datasource:
    url: jdbc:mysql://localhost:3306/coffeesmachine?createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

build:
  version: 1.0

account: 
  message: "Wellcome to prod"
  details:
    name : "ok"
    info : "test"
    mail : "{cypher}0eae0fdd8796be3dcac25889423b16d56794a30ebdee4c3c4c136398a9716fe7"
  phone:
  - "010230306"


